swagger: "2.0"
info:
  title: "Swagger API documentation"
  description: >
    This is an API documentation with all endpoint actions
  version: "1.0.0"
host: "localhost:8080"
schemes:
  - "http"
tags:
  - name: Users
    description: User related actions
  - name: Templates
    description: Template related actions
  - name: Template groups
    description: Template group related actions
  - name: Template group questions
    description: Template group question related actions
  - name: Version
    description: App version
  - name: Info
    description: App information related actions

paths:
  /api/v1/user/new:
    post:
      tags:
        - Users
      summary: "User registration"
      description: "Creates new user"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            type: "object"
            required:
              - email
              - password
              - confirmPassword
              - role
            properties:
              email:
                type: "string"
                example: "username@email.com"
              role:
                type: "string"
                example: "user"
              password:
                type: "string"
                example: "secret123"
              confirmPassword:
                type: "string"
                example: "secret123"
      responses:
        200:
          description: "Registration is successful"
          schema:
            type: "string"
        400:
          description: "Bad request happened"
  /api/v1/user/auth:
    post:
      tags:
        - Users
      summary: "Authentication request"
      description: "Authenticates user based on email and password"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "E-mail and password to authenticate"
          required: true
          schema:
            type: "object"
            required:
              - email
              - password
            properties:
              email:
                type: "string"
                example: "username@email.com"
              password:
                type: "string"
                example: "secret123"
              rememberMe:
                type: "boolean"
                example: false

      responses:
        200:
          description: "Credentials are correct"
          schema:
            type: "string"
        401:
          description: "Wrong credentials"
        400:
          description: "Bad request happened"
  /api/v1/template/new:
    post:
      tags:
        - Templates
      summary: "Add new assessment template"
      description: "Add new assessment template"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: header
          name: auth-token
          description: Authentication JWT header
          required: true
          schema:
            $ref: "#/definitions/Authentication"
        - in: body
          name: body
          required: true
          schema:
            type: object
            required:
              - name
            properties:
              name:
                type: string
                example: My new assessment template name.
      responses:
        201:
          description: "Added successfully"
          schema:
            $ref: '#/definitions/Template'
        400:
          description: "Validation error"
        500:
          $ref: '#/responses/500'
  /api/v1/templates:
    get:
      tags:
        - Templates
      summary: "Get templates"
      description: "Get assessment template list"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: header
          name: auth-token
          description: Authentication JWT header
          required: true
          schema:
            $ref: "#/definitions/Authentication"
      responses:
        200:
          description: "Assessment template's list"
          schema:
            $ref: '#/definitions/Templates'
        401:
          description: "Unauthorized"
        500:
          $ref: '#/responses/500'
  /api/v1/template/details:
    get:
      tags:
        - Templates
      description: "Get templates details with questions and groups"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: header
          name: auth-token
          description: Authentication JWT header
          required: true
          schema:
            $ref: "#/definitions/Authentication"
      responses:
        200:
          description: "Template details list"
          schema:
            $ref: '#/definitions/Template.Details'
        401:
          description: "Unauthorized"
        500:
          $ref: '#/responses/500'
  /api/v1/template/group/new:
    post:
      tags:
        - Template groups
      description: Creates new template group
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: header
          name: auth-token
          description: Authentication JWT header
          required: true
          schema:
            $ref: "#/definitions/Authentication"
        - in: body
          name: body
          required: true
          schema:
            type: object
            required:
              - templateId
              - text
            properties:
              text:
                type: string
                example: My new template group name.
              templateId:
                type: number
                example: 1
      responses:
        201:
          description: "Added successfully"
          schema:
            $ref: '#/definitions/Template.Group'
        400:
          description: "Validation error"
        500:
          $ref: '#/responses/500'
  /api/v1/template/groups:
    get:
      tags:
        - Template groups
      description: Get template group list
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: header
          name: auth-token
          description: Authentication JWT header
          required: true
          schema:
            $ref: "#/definitions/Authentication"
      responses:
        200:
          description: "Template group list"
          schema:
            $ref: '#/definitions/Template.Groups'
        401:
          description: "Unauthorized"
        500:
          $ref: '#/responses/500'
  /api/v1/template/group/question/new:
    post:
      tags:
        - Template group questions
      description: Creates new template group question
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: header
          name: auth-token
          description: Authentication JWT header
          required: true
          schema:
            $ref: "#/definitions/Authentication"
        - in: body
          name: body
          required: true
          schema:
            type: object
            required:
              - groupId
              - text
            properties:
              text:
                type: string
                example: My new template group name.
              groupId:
                description: Template question group Id
                type: number
                example: 1
      responses:
        201:
          description: "Added successfully"
          schema:
            $ref: '#/definitions/Template.Group.Question'
        400:
          description: "Validation error"
        500:
          $ref: '#/responses/500'
  /health-check:
    get:
      tags:
        - Info
        - Version
      summary: "Check the status of the service"
      description: "If the service is up and running correctly the response will be 'UP'"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "Service is up and healthy"
          schema:
            $ref: "#/definitions/Health"
        500:
          $ref: '#/responses/500'

responses:
  500:
    description: Internal Server Error
    schema:
      $ref: '#/definitions/Error'

definitions:
  Health:
    type: object
    properties:
      status:
        type: string
        enum:
          - UP
          - DOWN
      version:
        type: string
        example: 1.0.0
  Template:
    type: object
    properties:
      id:
        type: number
        example: 1
      name:
        type: string
        example: Ethical Trading Initiative
      status?:
        type: string
        enum:
          - active
          - hidden
        example: active
      updatedAt?:
        type: string
        example: '2021-05-15T14:10:49.000Z'
      createdAt?:
        type: string
        example: '2021-05-15T14:10:49.000Z'
  Templates:
    type: array
    items:
      $ref: '#/definitions/Template'
  Template.Group:
    type: object
    properties:
      id:
        type: number
        example: 1
      templateId:
        type: number
        example: 1
      text:
        type: string
        example: Employment is freely chosen
      status?:
        type: string
        enum:
          - active
          - hidden
        example: active
      updatedAt?:
        type: string
        example: '2021-05-15T14:10:49.000Z'
      createdAt?:
        type: string
        example: '2021-05-15T14:10:49.000Z'
  Template.Groups:
    type: array
    items:
      $ref: '#/definitions/Template.Group'
  Template.Group.Question:
    type: object
    properties:
      id:
        type: number
        example: 1
      groupId:
        description: Question group Id
        type: number
        example: 1
      text:
        description: Question text
        type: string
        example: There is no forced, bonded or involuntary prison labour
      status?:
        type: string
        enum:
          - active
          - hidden
          - removed
        example: active
      updatedAt?:
        type: string
        example: '2021-05-15T14:10:49.000Z'
      createdAt?:
        type: string
        example: '2021-05-15T14:10:49.000Z'
  Template.Details:
    type: array
    items:
      allOf:
        - $ref: '#/definitions/Template'
        - type: object
          properties:
            groups:
              type: array
              items:
                allOf:
                  - $ref: '#/definitions/Template.Group'
                  - type: object
                    properties:
                      questions:
                        type: array
                        items:
                          allOf:
                            - $ref: '#/definitions/Template.Group.Question'
  Authentication:
    type: string
    format: JWT
    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJiYXNpYyIsImVtYWlsIjoidXNlcm5hbWVAZW1haWwuY29tIiwiaWF0IjoxNjIwOTQzNzY5LCJleHAiOjI4MjA5NDM3Njl9.yW5cwC_sOlQwWtJKIcReFX17YPwZG3OeO1MzA-hGbjY
  Error:
    type: string
    example: Internal Server Error


